# This is a basic workflow to help you get started with Actions

name: Proselint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - name: lint prose
        uses: actions/checkout@v3
        
      - name: use proselint to checkout md files
        run: | 
          pip install proselint
          proselint *.md
          
      - name: use write-good to checkout md files
        run: |
          npm install -g write-good
          write-good *.md
